### ISSUE TITLE
Create login

### ISSUE THREAD

**Issue by zaynalam** [kesh92/Project_51#6]
1) Allow user to sign up normally
2) Allow user to sign up Google
3) Allow user to login normally
4) allow user to login Google

**Comment by zaynalam** [comment]
1) Allow user  data to be entered and captured in a database

**Comment by kesh92** [comment]
We would not need Google sign-up

**Comment by zaynalam** [comment]
1) Login + signup done

**Comment by zaynalam** [comment]
1) Need to know how you created pop up for email '@' notification
2) have to make remember me
3) will add pop conditions rather than going to a new page where applicable

**Comment by kesh92** [comment]
1. The pop-up happens because the input type for the email form is set as 'email'. I think HTML5 automatically does this by its inbuilt javascript library
2. Please open a new ticket to keep track of the remember me feature, though it's fine if it doesn't work by the end of the sprint as it wont affect major functionality of the page
3. I've opened #7 to accommodate this
